version: '1'

services:
  go-sns:
    image: "postgres:11"
    container_name: go-sns
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sns-db
    ports:
      - "5435:5432"
    volumes:
      - ./go_sns_volumes:/home/go_sns_volumes
      - ./sql_scripts:/docker-entrypoint-initdb.d

volumes:
  go_sns_volumes:
    external: true
